trunk/Implementacao/fa7-shoppingvirtual/src/br/com/seteshop/controle/LoginBean.java
package br.com.seteshop.controle;

import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
 
import br.com.seteshop.negocio.ClienteFachada;
import br.com.seteshop.negocio.LojistaFachada;
import br.com.seteshop.negocio.modelo.Cliente;
import br.com.seteshop.negocio.modelo.Lojista;
import br.com.seteshop.negocio.modelo.Usuario;

public class LoginBean {
	private String login;
	private String senha;
	private String perfil;
	private String mensagemDeErro;
	private String titulo;
	private Cliente cliente;
	private Lojista lojista;
	private String admin;
	
	public String getAdmin() {
		return admin;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Lojista getLojista() {
		return lojista;
	}

	public void setLojista(Lojista lojista) {
		this.lojista = lojista;
	}

	/**
	 * @return Returns the titulo.
	 */
	public String getTitulo() {
		return titulo;
	}

	/**
	 * @param titulo
	 *            The titulo to set.
	 */
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getPerfil() {
		return perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	private void limpar_login() {
		mensagemDeErro = null;
		login = null;
		senha = null;

		cliente = null;
		lojista = null;
		admin = null;
	}

	public LoginBean() {
	}

	public String logarComoCliente() throws Exception {
		try {

			ClienteFachada clientefachada = new ClienteFachada();

			cliente = null;

			cliente = clientefachada.recuperarClientePorEmailESenha(login,
					senha);

			Cliente cliente_temp = cliente;

			limpar_login();

			cliente = cliente_temp;

			if (cliente != null) {
				return "sucesso_cliente";
			} else {
				return "error";
			}
		} catch (Exception e) {

		}
		return "";
	}

	public String logarComoLojista() throws Exception {
		try {

			LojistaFachada lojistafachada = new LojistaFachada();

			lojista = null;

			lojista = lojistafachada.recuperarLojistaPorEmailESenha(login,
					senha);

			Lojista lojista_temp = lojista;

			limpar_login();

			lojista = lojista_temp;

			if (lojista != null) {
				return null;
			} else {
				return "error";
			}
		} catch (Exception e) {

		}
		return "";
	}
	
	public String logarComoAdmin() throws Exception {

		admin = null;
		if ((login.equals("zzz")) && (senha.equals("zzz"))) {
			admin = login;
		}
		return "";
	}

	/**
	 * @return Returns the mensagemDeErro.
	 */
	public String getMensagemDeErro() {
		return mensagemDeErro;
	}

	/**
	 * @param mensagemDeErro
	 *            The mensagemDeErro to set.
	 */
	public void setMensagemDeErro(String mensagemDeErro) {
		this.mensagemDeErro = mensagemDeErro;
	}

	public String sair() {

		limpar_login();

		return "logoff";
	}

	public String sairLojista() {

		limpar_login();

		return "logoff_lojista";
	}

	public String sairAdmin() {

		limpar_login();

		return "logoff_admin";
	}

}

trunk/Implementacao/fa7-shoppingvirtual/src/br/com/seteshop/controle/ManterPaginaPrincipalBean.java
/*
 * Created on 26/08/2007
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
package br.com.seteshop.controle;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;

import br.com.seteshop.exceptions.ProdutoException;
import br.com.seteshop.negocio.DepartamentoFachada;
import br.com.seteshop.negocio.LojaFachada;
import br.com.seteshop.negocio.ProdutoFachada;
import br.com.seteshop.negocio.SecaoFachada;
import br.com.seteshop.negocio.modelo.Departamento;
import br.com.seteshop.negocio.modelo.Loja;
import br.com.seteshop.negocio.modelo.Produto;
import br.com.seteshop.negocio.modelo.Secao;

public class ManterPaginaPrincipalBean {

	//Objetos utilizados pela pagina
	private Long idSecao;
	private Secao secao;
	private Departamento departamento;
	
	private Long idLoja;
	private Long idDepartamento;
	private Loja loja;
	private Produto produto;

	private List<Secao> secoes;
	private List<Departamento> departamentos;
	private List<Loja> lojas;
	private List<Produto> produtos;
	private List<Produto> produtos2;
	
	private List<Long> listaIdsDepartamentos;
	
	//Objetos para acesso ao negocio
	private SecaoFachada secaoFachada;
	private DepartamentoFachada departamentoFachada;
	private LojaFachada lojaFachada;
	private ProdutoFachada produtoFachada;
	
	private String mensagemDeErro;
	
	/**
	 * @return Returns the mensagemDeErro.
	 */
	public String getMensagemDeErro() {
		return mensagemDeErro;
	}

	/**
	 * @param mensagemDeErro The mensagemDeErro to set.
	 */
	public void setMensagemDeErro(String mensagemDeErro) {
		this.mensagemDeErro = mensagemDeErro;
	}

	public ManterPaginaPrincipalBean() {
		// TODO Auto-generated constructor stub
		secaoFachada = new SecaoFachada();
		departamentoFachada = new DepartamentoFachada();
		lojaFachada = new LojaFachada();
		produtoFachada = new ProdutoFachada();
	}
	
	@PostConstruct
	public void init() {
		
		if (secao == null) {
			secao = new Secao();
		}
		
		if (secaoFachada == null) {
			secaoFachada = new SecaoFachada();
		}
		
		if( secoes == null ){
			secoes = new ArrayList<Secao>();
		}
		
		secoes = secaoFachada.findAll();
		
		if (departamento == null) {
			departamento = new Departamento();
		}
		
		if (departamentoFachada == null) {
			departamentoFachada = new DepartamentoFachada();
		}
		
		if( departamentos == null ){
			departamentos = new ArrayList<Departamento>();
		}
		
		departamentos = departamentoFachada.findAll();
		
		if (loja == null) {
			loja = new Loja();
		}
		
		if (lojaFachada == null) {
			lojaFachada = new LojaFachada();
		}
		
		if( lojas == null ){
			lojas = new ArrayList<Loja>();
		}
		
		lojas = secoes.get(0).getLojas();
		
		if (produto == null) {
			produto = new Produto();
		}
		
		if (produtoFachada == null) {
			produtoFachada = new ProdutoFachada();
		}
		
		if( produtos == null ){
			produtos = new ArrayList<Produto>();
		}
		
		produtos = produtoFachada.findAll();
		
	}
	
	private void pegaParametroIdSecao() {
		FacesContext context = FacesContext.getCurrentInstance();
		Map<String,String> resquestParams = context.getExternalContext().getRequestParameterMap();
		if(resquestParams.get("id") != null && !resquestParams.get("id").toString().isEmpty()){
			setIdSecao(Long.valueOf(resquestParams.get("id").toString()));
		}else{
			setIdSecao(new Long(0));
		}
	}
	
	private void pegaParametroIdLoja(){
		FacesContext context = FacesContext.getCurrentInstance();
		Map<String,String> resquestParams = context.getExternalContext().getRequestParameterMap();
		if(resquestParams.get("id") != null && !resquestParams.get("id").toString().isEmpty()){
			setIdLoja(Long.valueOf(resquestParams.get("id").toString()));
		}else{
			setIdLoja(new Long(0));
		}
	}
	
	private void pegaParametroIdDepartamento(){
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String,String> resquestParams = context.getExternalContext().getRequestParameterMap();
        if(resquestParams.get("id") != null && !resquestParams.get("id").toString().isEmpty()){
            setIdDepartamento(Long.valueOf(resquestParams.get("id").toString()));
        }else{
            setIdDepartamento(new Long(0));
        }
    }

	public Long getIdSecao() {
		return idSecao;
	}

	public void setIdSecao(Long id) {
		this.idSecao = id;
	}

	/**
	 * @return Returns the secao.
	 */
	public Secao getSecao() {
		return secao;
	}

	/**
	 * @param secao The secao to set.
	 */
	public void setSecao(Secao secao) {
		this.secao = secao;
	}
	
	/**
	 * @return Returns the secoes.
	 */
	public List<Secao> getSecoes() {
		return secoes;
	}

	/**
	 * @param secao
	 */
	public void setSecoes(List<Secao> secoes) {
		this.secoes = secoes;
	}
	
	public Departamento getDepartamento() {
		return departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public Loja getLoja() {
		return loja;
	}

	public void setLoja(Loja loja) {
		this.loja = loja;
	}

	public List<Departamento> getDepartamentos() {
		return departamentos;
	}

	public void setDepartamentos(List<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	public List<Loja> getLojas() {
		return lojas;
	}

	public void setLojas(List<Loja> lojas) {
		this.lojas = lojas;
	}

	public SecaoFachada getSecaoFachada() {
		return secaoFachada;
	}

	public void setSecaoFachada(SecaoFachada secaoFachada) {
		this.secaoFachada = secaoFachada;
	}

	public DepartamentoFachada getDepartamentoFachada() {
		return departamentoFachada;
	}

	public void setDepartamentoFachada(DepartamentoFachada departamentoFachada) {
		this.departamentoFachada = departamentoFachada;
	}

	public LojaFachada getLojaFachada() {
		return lojaFachada;
	}

	public void setLojaFachada(LojaFachada lojaFachada) {
		this.lojaFachada = lojaFachada;
	}
	
	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public List<Produto> getProdutos() {
		return produtos;
	}

	public void setProdutos(List<Produto> produtos) {
		this.produtos = produtos;
	}

	public ProdutoFachada getProdutoFachada() {
		return produtoFachada;
	}

	public void setProdutoFachada(ProdutoFachada produtoFachada) {
		this.produtoFachada = produtoFachada;
	}

	//Métodos 
	
	public String pesquisarSecao() {
		secoes = secaoFachada.recuperarSecoesPorCodigoOuNome(secao);	
		return null;
	}
	
	public List<Secao> getListarTodasSecoes() {
		secoes = secaoFachada.findAll();
		if ((secoes != null) && (!secoes.isEmpty()) && (secao == null))
			secao = secoes.get(0);
		return secoes;
	}
	
	public String recuperarLojasDaSecao() {
		pegaParametroIdSecao();
		
		if ((getIdSecao() != null) && (getIdSecao().longValue() > 0))
			secao = secaoFachada.recuperarSecao(getIdSecao());
		
		return null;
	}
	
	public String recuperarProdutosDaLoja() {
		pegaParametroIdLoja();
		setIdDepartamento(null);
		return null;
	}
	
	public String recuperarProdutosDoDepartamento() {
	    pegaParametroIdDepartamento();
	    setIdLoja(null);
        return null;
    }
	
	public String pesquisarDepartamento() {
		departamentos = departamentoFachada.recuperarDepartamentosPorCodigoOuNome(departamento);
		return null;
	}
	
	public List<Departamento> getListarTodosDepartamentos() {
		return departamentoFachada.findAll();
	}
	
	public String pesquisarLoja() {
		lojas = lojaFachada.recuperarLojasPorCodigoOuNome(loja);
		return null;
	}
	
	public List<Loja> getListarLojasDaSecao() {
		if(secao != null && secao.getLojas() != null)
			lojas = secao.getLojas();	
		return lojas;
	}
	
	public List<Produto> getListarProdutosDaLojaDepartamento() throws ProdutoException {
		if(getIdLoja() != null && getIdLoja().longValue() > 0) {
			produtos2 = produtoFachada.recuperarProdutosPorCodigoLoja(getIdLoja());
	    }else if (getIdDepartamento() != null && getIdDepartamento().longValue() > 0) {
	        produtos2 = produtoFachada.recuperarProdutosPorCodigoDepartamento(getIdDepartamento());
	    }
		return produtos2;
	}
	
	public String pesquisarProduto() {
		produtos = produtoFachada.recuperarProdutosPorCodigoOuNome(produto);
		return null;
	}
	
	public String getListarTodosProdutos() {
		produtos = produtoFachada.findAll();	
		return null;
	}
	
	public List<Produto> getListarTodosProdutosPrincipais() {
		produtos = produtoFachada.findAll();	
		return produtos;
	}

	public void setIdLoja(Long idLoja) {
		this.idLoja = idLoja;
	}

	public Long getIdLoja() {
		return idLoja;
	}

    public void setIdDepartamento(Long idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    public Long getIdDepartamento() {
        return idDepartamento;
    }

}

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/contato.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
   	xmlns:c="http://java.sun.com/jstl/core" 
	template="/paginas/templates/template.xhtml">
		
    <ui:define name="espaco_1">
		<ui:include src="/paginas/topo.xhtml"/>
	</ui:define>
	
	<ui:define name="meio">
	
		<div id="areaProdutos">
		
			<h3>Contato</h3>
			
			<p>
			
				Para entrar em contato com a equipe de desenvolvimento, segue a lista de e-mails:
				
				<br /><br />
				
				Vitor Braga (Programador Senior Plus)<br />
				vitor.leitebraga@gmail.com
				
				<br /><br />
				
				Arthur Franklin Accioly<br />
				arthur_info@yahoo.com.br
				
				<br /><br />
				
				Marcelo Siqueira Boavista<br />
				marceloboavista@gmail.com
				
				<br /><br />
				
				Paulo Henrique Holanda do Amaral<br />
				ph.hamaral@gmail.com
				
				<br /><br />
				
				Carlos Alberto Fernandes Medeiros<br />
				carlosfdj@yahoo.com.br
				
				<br /><br />
				
				Régis Patrick Silva Simão<br />
				regissimao@yahoo.com.br
				
			</p>
			
		</div>
		
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/editarCliente.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jstl/core"
	template="/paginas/templates/template.xhtml">

	<ui:define name="conteudoPrincipal">
		<div id="conteudoPrincipal"></div>
	</ui:define>

	<h:form>
		<h:panelGrid columns="3" align="center">
			<h:outputLabel for="nome" value="Nome" />
			<h:inputText id="nome" value="#{manterClienteBean.cliente.nome}"
				required="true" />
			<h:message for="nome" class="mensagemDeErro" />
			<h:outputLabel for="sobrenome" value="Sobrenome" />
			<h:inputText id="sobrenome"
				value="#{manterClienteBean.cliente.sobrenome}" required="true" />
			<h:message for="sobrenome" class="mensagemDeErro" />
			<h:outputLabel for="email" value="Email" />
			<h:inputText id="email" value="#{manterClienteBean.cliente.email}"
				required="true" />
			<h:message for="email" class="mensagemDeErro" />
		</h:panelGrid>
		<h:commandButton value="Salvar"
						action="#{manterClienteBean.atualizarCliente}" />
	</h:form>
</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/empresa.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
   	xmlns:c="http://java.sun.com/jstl/core" 
	template="/paginas/templates/template.xhtml">
		
    <ui:define name="espaco_1">
		<ui:include src="/paginas/topo.xhtml"/>
	</ui:define>
	
	<ui:define name="meio">
	
		<div id="areaProdutos">
		
			<h3>Empresa</h3>
			
			<p>
				O 7Shop é um produto que foi desenvolvido pelos alunos da Faculdade 7 de Setembro.<br />
				O objetivo desse projeto era ensinar aos alunos na prática o desenvolvimento de um <br />
				produto utilizando os conhecimentos e metodologias utilizadas em todas as disciplinas <br />
				técnicas do curso.
				
				<br /><br /> 

				O sistema é um Shopping Virtual voltado para LOJISTAS E CLIENTES. Nele o Lojista matêm <br />
				os cadastros das suas Lojas,  Departamentos, Sessões e seus Produtos. Já os  Clientes do <br />
				shopping podem efetuar suas compras, manter seus carrinhos de compras e suas formas de <br />
				pagamentos.	
			</p>
			
		</div>
		
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/footer.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">
	
	<div id="rodape">
		<adress>Desenvolvido por Estagio 3 - 2010.2</adress>
	</div>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
   	xmlns:c="http://java.sun.com/jstl/core" 
	template="/paginas/templates/template.xhtml">
		
	<ui:define name="conteudoPrincipal">
		<div id="conteudoPrincipal">
			<div id="produtosPrincipais">
				<h3>Produtos Destaque</h3>
					<ul id="demoOne">
						<c:forEach items="#{manterPaginaPrincipalBean.listarTodosProdutosPrincipais}"  var="produtoPrincipal">
							<li><a href=""><img src="#{facesContext.externalContext.requestContextPath}/imagens/banner/#{produtoPrincipal.imagem}" height="263"  border="0"/></a></li>
						</c:forEach>
					</ul>
				<br clear="all" />
			</div>
			
			<div id="produtos">
				<h3>Produtos</h3>
				
						<c:forEach items="#{manterPaginaPrincipalBean.listarProdutosDaLojaDepartamento}"  var="produto">
							<div class="borda-arredondada" style="float:left; margin-left:10px;">
										<h3><h:outputText value="#{produto.nome}"  /></h3>  <br />
										<p><h:outputText value="#{produto.descricao}"  /></p>  <br />
										
										<p><h:outputLabel value="Estoque" /></p> 
										<p><h:outputText value="#{produto.quantidadeEstoque}"  /></p>  <br />
										
										<p><h:outputLabel  value="Preço" /></p> 
										<p>R$<h:outputText value="#{produto.preco}"  /></p> <br />
										<h:message class="mensagemDeErro" />
							</div>
						</c:forEach>
				</div>
					
			</div>
		
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/indexAdmin.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
   	xmlns:c="http://java.sun.com/jstl/core" 
	template="/paginas/templates/templateAdmin.xhtml">
		 
	<ui:define name="conteudoPrincipal">
		<div id="conteudoPrincipal">	
		</div>
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/indexCliente.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
   	xmlns:c="http://java.sun.com/jstl/core" 
	template="/paginas/templates/templateLojista.xhtml">
		 
	<ui:define name="conteudoPrincipal">
		<div id="conteudoPrincipal">	
		</div>
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/indexLojista.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
   	xmlns:c="http://java.sun.com/jstl/core" 
	template="/paginas/templates/templateLojista.xhtml">
		 
	<ui:define name="conteudoPrincipal">
		<div id="conteudoPrincipal">	
		</div>
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/listaClientes.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jstl/core">
	
	<ui:define name="conteudoPrincipal">
		<div id="conteudoPrincipal"></div>
	</ui:define>
    <h:form>
	<h:dataTable var="item" border="1" cellpadding="2" cellspacing="0"
		value="#{manterClienteBean.todosClientes}" width="450px">
		<h:column>
			<h:outputText value="#{item.email}" />
		</h:column>
		<h:column>
		<h:commandLink value="Editar"
						action="#{manterClienteBean.editarCliente}" />
		</h:column>				
	</h:dataTable>
	</h:form>
</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/login.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/paginas/templates/template.xhtml">

	<ui:define name="espaco_1">
		<ui:include src="/paginas/topo.xhtml" />
	</ui:define>

	<ui:define name="meio">
		<h:form>
			<h:panelGrid columns="3" align="center">
				<h:outputLabel for="login" value="Login"/>
				<h:inputText id="login" value="#{loginBean.login}" required="true">
					<f:validateLength minimum="3" maximum="80" />
				</h:inputText>
				<h:message for="login" class="mensagemDeErro" />
				<h:outputLabel for="senha" value="Senha" />
				<h:inputSecret id="senha" value="#{loginBean.senha}" required="true">
					<f:validateLength minimum="3" maximum="20" />
				</h:inputSecret>
				<h:message for="senha" class="mensagemDeErro" />
			</h:panelGrid>
			<br />
			<table align="center">
				<tr>
					<td><h:commandButton value="Entrar"
						action="#{loginBean.logar}" /></td>
					<td><h:commandButton value="Cancelar" action="cancelar"
						immediate="true" /></td>
				</tr>
			</table>
			<h:outputLabel for="mensagemDeErro"
				value="#{loginBean.mensagemDeErro}" class="mensagemDeErro"
				align="center" />
		</h:form>
	</ui:define>

</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/topo.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<div id="logo">
		<img src="http://localhost:8080/7shop/imagens/7Shop.png"/>
	</div>
	
	<div id="login">
		<h:form>
			<h:inputText value="#{loginBean.login}">Login:</h:inputText>
			<h:inputText value="#{loginBean.senha}">Senha:</h:inputText>
			<c:if test="#{loginBean.cliente == null and loginBean.cliente == null}">
				<h:commandLink id="submitLogin" value="Logar" action="login" class="branco" />
			</c:if>
			
			<c:if test="#{loginBean.cliente != null || loginBean.cliente != null}">
				<h:commandLink id="submitLogoff" value="Logoff" action="#{loginBean.sair}" />
			</c:if>
		</h:form>
		<a class="branco" href="/7shop/paginas/manter_cliente/ManterCliente_incluir.faces"  style="margin-right:20px;">Cadastrar Cliente</a>
		<a class="branco" href="/7shop/paginas/manter_lojista/ManterLojista_incluir.faces">Cadastrar Lojista</a>
		
	</div>
	<br/>
	
	<!-- Possivel colocação mais tarde no desenvolvimento. Dependendo do concenso entre os desenvolvedores
 	<div id="menu" class="mgl20">
		<h:form>
			<h:commandLink id="btHome" value="Home" action="home" /> | 
			
			<h:commandLink id="btEmpresa" value="Empresa" action="empresa" /> | 
			
			<h:commandLink id="btContato" value="Contato" action="contato" /> | 
		</h:form>
	</div>
	
	-->
	
	<div id="pesquisa">
		<h:form>
			<h:inputText class="inputPesquisa" value="#{produtoBean.produto.nome}"></h:inputText>
			<h:commandButton class="btPesquisa" value="Pesquisar"
				action="#{produtoBean.pesquisarProdutoporNome}" />
		</h:form> 
	</div>
	
</ui:composition>

trunk/Implementacao/fa7-shoppingvirtual/WebContent/paginas/topoLogin.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<div id="logo">
		<img src="http://localhost:8080/7shop/imagens/7Shop.png"/>
	</div>


<div id="menu" class="mgl20"><h:form>
		<h:commandLink id="btHome" value="Home" action="home" /> | 
		
		<h:commandLink id="btEmpresa" value="Empresa" action="empresa" /> | 
		
		<h:commandLink id="btContato" value="Contato" action="contato" /> | 
		
	</h:form></div>

</ui:composition>